using System.Text.Json;
using System.Text.Json.Serialization;

namespace Runesmith.Lsp.Protocol;

/// <summary>Source-generated serialization of the protocol types: camelCase names, nulls left out.</summary>
/// <summary>The source-generated JSON serialization of the protocol types, for clients and servers alike.</summary>
[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
[JsonSerializable(typeof(InitializeParams))]
[JsonSerializable(typeof(InitializeResult))]
[JsonSerializable(typeof(DidOpenTextDocumentParams))]
[JsonSerializable(typeof(DidChangeTextDocumentParams))]
[JsonSerializable(typeof(DidSaveTextDocumentParams))]
[JsonSerializable(typeof(DidCloseTextDocumentParams))]
[JsonSerializable(typeof(PublishDiagnosticsParams))]
[JsonSerializable(typeof(CompletionParams))]
[JsonSerializable(typeof(CompletionItem))]
[JsonSerializable(typeof(CompletionItem[]))]
[JsonSerializable(typeof(CompletionList))]
[JsonSerializable(typeof(TextDocumentPositionParams))]
[JsonSerializable(typeof(ReferenceParams))]
[JsonSerializable(typeof(Hover))]
[JsonSerializable(typeof(SignatureHelp))]
[JsonSerializable(typeof(Location))]
[JsonSerializable(typeof(Location[]))]
[JsonSerializable(typeof(LocationLink))]
[JsonSerializable(typeof(ShowMessageParams))]
[JsonSerializable(typeof(LogMessageParams))]
[JsonSerializable(typeof(ProgressParams))]
[JsonSerializable(typeof(ConfigurationParams))]
[JsonSerializable(typeof(WorkspaceFolder[]))]
[JsonSerializable(typeof(JsonElement?[]))]
[JsonSerializable(typeof(Dictionary<string, object>))]
[JsonSerializable(typeof(Dictionary<string, long>))]
[JsonSerializable(typeof(CodeActionParams))]
[JsonSerializable(typeof(CodeAction))]
[JsonSerializable(typeof(Command))]
[JsonSerializable(typeof(RenameParams))]
[JsonSerializable(typeof(WorkspaceEdit))]
[JsonSerializable(typeof(TextEdit[]))]
[JsonSerializable(typeof(TextDocumentEdit))]
[JsonSerializable(typeof(CreateFile))]
[JsonSerializable(typeof(RenameFile))]
[JsonSerializable(typeof(DeleteFile))]
[JsonSerializable(typeof(DocumentFormattingParams))]
[JsonSerializable(typeof(DocumentRangeFormattingParams))]
[JsonSerializable(typeof(InlayHintParams))]
[JsonSerializable(typeof(InlayHint))]
[JsonSerializable(typeof(InlayHint[]))]
[JsonSerializable(typeof(InlayHintLabelPart))]
[JsonSerializable(typeof(CodeLensParams))]
[JsonSerializable(typeof(CodeLens))]
[JsonSerializable(typeof(CodeLens[]))]
[JsonSerializable(typeof(ExecuteCommandParams))]
[JsonSerializable(typeof(ApplyWorkspaceEditParams))]
[JsonSerializable(typeof(ApplyWorkspaceEditResult))]
[JsonSerializable(typeof(DocumentHighlight[]))]
[JsonSerializable(typeof(DocumentParams))]
[JsonSerializable(typeof(DocumentSymbol))]
[JsonSerializable(typeof(SymbolInformation))]
[JsonSerializable(typeof(SymbolInformation[]))]
[JsonSerializable(typeof(WorkspaceSymbolParams))]
[JsonSerializable(typeof(FoldingRange[]))]
[JsonSerializable(typeof(SemanticTokensLegend))]
[JsonSerializable(typeof(SemanticTokens))]
[JsonSerializable(typeof(SemanticTokensRangeParams))]
[JsonSerializable(typeof(SelectionRange[]))]
[JsonSerializable(typeof(SelectionRangeParams))]
[JsonSerializable(typeof(HierarchyItem[]))]
[JsonSerializable(typeof(HierarchyItemParams))]
[JsonSerializable(typeof(CallHierarchyIncomingCall[]))]
[JsonSerializable(typeof(CallHierarchyOutgoingCall[]))]
[JsonSerializable(typeof(JsonElement))]
[JsonSerializable(typeof(object))]
public sealed partial class LspJsonContext : JsonSerializerContext;
